# Tensorflow 세 가지 모델 작성


### Data Slicing

In [1]:
#import, 함수 선언 부
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

#data slicing
data = np.loadtxt("data/wdbc_modified.csv", delimiter=",")
print(data.shape)

x_train = data[:, 0:30]
y_train = data[:, 30:]
x_new = x_train[15:25]

print(x_train.shape)
print(y_train.shape)
print(x_train[:10])
print(y_train[:10])

(569, 31)
(569, 30)
(569, 1)
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e

***
# Sequential Model
### Sequential Model 생성

In [2]:
sqModel = keras.Sequential()
sqModel.add(layers.Dense(64, input_dim=30, activation="relu"))
sqModel.add(layers.Dense(32, activation="relu"))
sqModel.add(layers.Dense(1, activation="sigmoid"))

sqModel.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1984      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 4,097
Trainable params: 4,097
Non-trainable params: 0
_________________________________________________________________


### Sequential Model 학습 수행

In [3]:
sqModel.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
history = sqModel.fit(x_train, y_train, epochs=500, batch_size=10)

Epoch 1/500


57/57 [==============================] - 1s 840us/step - loss: 2.5147 - accuracy: 0.6503
Epoch 2/500
57/57 [==============================] - 0s 759us/step - loss: 0.6389 - accuracy: 0.8295
Epoch 3/500
57/57 [==============================] - 0s 751us/step - loss: 0.3127 - accuracy: 0.8875
Epoch 4/500
57/57 [==============================] - 0s 733us/step - loss: 0.2489 - accuracy: 0.9104
Epoch 5/500
57/57 [==============================] - 0s 616us/step - loss: 0.6594 - accuracy: 0.8366
Epoch 6/500
57/57 [==============================] - 0s 952us/step - loss: 0.5378 - accuracy: 0.8682
Epoch 7/500
57/57 [==============================] - 0s 759us/step - loss: 0.3356 - accuracy: 0.9033
Epoch 8/500
57/57 [==============================] - 0s 769us/step - loss: 0.2922 - accuracy: 0.9051
Epoch 9/500
57/57 [==============================] - 0s 777us/step - loss: 0.3506 - accuracy: 0.8981
Epoch 10/500
57/57 [==============================] - 0s 778us/step - loss: 0.3083 - accuracy: 0.8946
E

### 알고 있는 y data에 대한 검증

In [4]:
score = sqModel.evaluate(x_train, y_train, batch_size=10)
print(score)

 1/57 [..............................] - ETA: 5s - loss: 9.0961e-04 - accuracy: 1.0000

57/57 [==============================] - 0s 706us/step - loss: 0.0602 - accuracy: 0.9701
[0.06018935143947601, 0.9701230525970459]


### 새로운 데이터 예측

In [5]:
y_predict = sqModel.predict(x_new)
print(y_predict)
print(y_train[15:25])

1/1 [==============================] - 0s 62ms/step
[[9.9999982e-01]
 [1.0000000e+00]
 [1.0000000e+00]
 [1.0000000e+00]
 [5.8491906e-04]
 [4.2832385e-06]
 [7.1823762e-11]
 [8.9971340e-01]
 [1.0000000e+00]
 [1.0000000e+00]]
[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


***
# Keras Functional API
### 모델 생성

In [6]:
inputs = keras.Input(shape=(30,), name="my_input")
x = layers.Dense(64, activation="relu", name="layers")(inputs)
x = layers.Dense(32, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
funcModel = keras.Model(inputs=inputs, outputs=outputs)

funcModel.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 my_input (InputLayer)       [(None, 30)]              0         
                                                                 
 layers (Dense)              (None, 64)                1984      
                                                                 
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 4,097
Trainable params: 4,097
Non-trainable params: 0
_________________________________________________________________


### 학습 수행

In [7]:
funcModel.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
history = funcModel.fit(x_train, y_train, epochs=500, batch_size=10)

Epoch 1/500


57/57 [==============================] - 1s 777us/step - loss: 4.2702 - accuracy: 0.7083
Epoch 2/500
57/57 [==============================] - 0s 765us/step - loss: 0.5774 - accuracy: 0.8664
Epoch 3/500
57/57 [==============================] - 0s 741us/step - loss: 0.4791 - accuracy: 0.8805
Epoch 4/500
57/57 [==============================] - 0s 760us/step - loss: 0.6345 - accuracy: 0.8647
Epoch 5/500
57/57 [==============================] - 0s 759us/step - loss: 0.2901 - accuracy: 0.9121
Epoch 6/500
57/57 [==============================] - 0s 760us/step - loss: 0.4086 - accuracy: 0.8998
Epoch 7/500
57/57 [==============================] - 0s 751us/step - loss: 0.3886 - accuracy: 0.8946
Epoch 8/500
57/57 [==============================] - 0s 760us/step - loss: 0.2892 - accuracy: 0.9121
Epoch 9/500
57/57 [==============================] - 0s 741us/step - loss: 0.3062 - accuracy: 0.9227
Epoch 10/500
57/57 [==============================] - 0s 750us/step - loss: 0.2374 - accuracy: 0.9121
E

### y data 통해 검증

In [8]:
#알고 있는 y data 통해 검증
score = funcModel.evaluate(x_train, y_train, batch_size=10)
print(score)

57/57 [==============================] - 0s 688us/step - loss: 0.0467 - accuracy: 0.9772
[0.04670329391956329, 0.9771528840065002]


### 새로운 데이터 통해 예측

In [9]:
y_predict = funcModel.predict(x_new)
print(y_predict)
print(y_train[15:25])

1/1 [==============================] - 0s 41ms/step
[[9.9995339e-01]
 [9.9992889e-01]
 [9.9999970e-01]
 [1.0000000e+00]
 [3.1345623e-04]
 [2.4196182e-05]
 [9.1815027e-06]
 [9.9200881e-01]
 [1.0000000e+00]
 [1.0000000e+00]]
[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


# Model Subclassing
### 모델 생성

In [10]:
class MyModel(keras.Model):
    def __init__(self):
        super().__init__()
        self.layer1 = layers.Dense(64, input_dim=30, activation="relu")
        self.layer2 = layers.Dense(32, activation="relu")
        self.output_layer = layers.Dense(1, activation="sigmoid")

    def call(self, inputs):
        _x = self.layer1(inputs)
        _x = self.layer2(_x)
        _outputs = self.output_layer(_x)
        return _outputs
    
clModel = MyModel() 

### 학습 수행

In [11]:
clModel.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
history = clModel.fit(x_train, y_train, epochs=500, batch_size=10)

Epoch 1/500
57/57 [==============================] - 1s 759us/step - loss: 3.0507 - accuracy: 0.7258
Epoch 2/500
57/57 [==============================] - 0s 733us/step - loss: 0.5643 - accuracy: 0.8735
Epoch 3/500
57/57 [==============================] - 0s 786us/step - loss: 0.5450 - accuracy: 0.8735
Epoch 4/500
57/57 [==============================] - 0s 769us/step - loss: 0.3368 - accuracy: 0.9104
Epoch 5/500
57/57 [==============================] - 0s 772us/step - loss: 0.6141 - accuracy: 0.8612
Epoch 6/500
57/57 [==============================] - 0s 775us/step - loss: 0.6006 - accuracy: 0.8787
Epoch 7/500
57/57 [==============================] - 0s 760us/step - loss: 1.3144 - accuracy: 0.8313
Epoch 8/500
57/57 [==============================] - 0s 751us/step - loss: 0.8766 - accuracy: 0.8629
Epoch 9/500
57/57 [==============================] - 0s 760us/step - loss: 1.2719 - accuracy: 0.8576
Epoch 10/500
57/57 [==============================] - 0s 741us/step - loss: 0.6620 - accura

### 데이터 검증

In [12]:
score = clModel.evaluate(x_train, y_train, batch_size=10)
print(score)

57/57 [==============================] - 0s 720us/step - loss: 0.0774 - accuracy: 0.9666
[0.07743429392576218, 0.9666081070899963]


### 데이터 예측

In [13]:
y_predict = clModel.predict(x_new)
print(y_predict)
print(y_train[15:25])

1/1 [==============================] - 0s 40ms/step
[[9.9929911e-01]
 [9.9990124e-01]
 [9.9999779e-01]
 [1.0000000e+00]
 [2.6309746e-03]
 [2.0984346e-04]
 [5.8204082e-06]
 [9.5020908e-01]
 [1.0000000e+00]
 [1.0000000e+00]]
[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
